Repository googleapis/python-bigquery-storage, pull requests merged in 2020-10, with the labels that each got.

#60 doc: update resource docstrings
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/test-samples.sh
  google/cloud/bigquery_storage_v1/services/big_query_read/client.py
  samples/quickstart/noxfile.py
  samples/to_dataframe/noxfile.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: partial

#72 docs: update to_dataframe sample to latest dependencies
  samples/to_dataframe/requirements.txt
Labels: cla: yes

#77 chore(python_library): change the docs bucket name
  .kokoro/docs/common.cfg
  synth.metadata
Labels: cla: yes, context: full

#79 fix: don't fail with 429 when downloading wide tables
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc_asyncio.py
  synth.py
  tests/system/v1/test_reader_v1.py
  tests/unit/gapic/bigquery_storage_v1/test_big_query_read.py
Labels: cla: yes

#80 feat: add public transport property and path formatting methods to client
  google/cloud/bigquery_storage_v1/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/base.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1/types/storage.py
  synth.metadata
  tests/unit/gapic/bigquery_storage_v1/test_big_query_read.py
Labels: automerge, cla: yes, context: partial

#83 chore(docs): update code of conduct of synthtool and templates
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full
