Repository googleapis/python-bigquery-storage, pull requests merged in 2020-11, with the labels that each got.

#91 docs: show inheritance in types reference
  docs/bigquery_storage_v1/types.rst
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc_asyncio.py
  scripts/fixup_bigquery_storage_v1_keywords.py
  synth.metadata
  tests/unit/gapic/bigquery_storage_v1/test_big_query_read.py
Labels: automerge, cla: yes, context: full

#86 docs: add intersphinx to proto-plus library
  docs/conf.py
  synth.metadata
Labels: automerge, cla: yes, context: full

#95 chore: re-generated to pick up changes from synthtool
  noxfile.py
  samples/quickstart/noxfile.py
  samples/to_dataframe/noxfile.py
  synth.metadata
Labels: cla: yes, context: partial

#93 chore: update synth.py to latest noxfile template
  noxfile.py
  synth.py
Labels: api: bigquerystorage, automerge, cla: yes

#96 chore: add blacken to template
  samples/quickstart/noxfile.py
  samples/to_dataframe/noxfile.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full
