Repository googleapis/python-bigquery-storage, pull requests merged in 2020-09, with the labels that each got.

#53 chore: change default retry policies timeouts (via synth)
  docs/conf.py
  google/cloud/bigquery_storage_v1/gapic/big_query_read_client.py
  google/cloud/bigquery_storage_v1/gapic/big_query_read_client_config.py
  google/cloud/bigquery_storage_v1/gapic/transports/big_query_read_grpc_transport.py
  google/cloud/bigquery_storage_v1/proto/arrow_pb2.py
  google/cloud/bigquery_storage_v1/proto/arrow_pb2_grpc.py
  google/cloud/bigquery_storage_v1/proto/avro_pb2.py
  google/cloud/bigquery_storage_v1/proto/avro_pb2_grpc.py
  google/cloud/bigquery_storage_v1/proto/storage_pb2.py
  google/cloud/bigquery_storage_v1/proto/storage_pb2_grpc.py
  google/cloud/bigquery_storage_v1/proto/stream_pb2.py
  google/cloud/bigquery_storage_v1/proto/stream_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta1/gapic/big_query_storage_client.py
  google/cloud/bigquery_storage_v1beta1/gapic/big_query_storage_client_config.py
  google/cloud/bigquery_storage_v1beta1/gapic/transports/big_query_storage_grpc_transport.py
  google/cloud/bigquery_storage_v1beta1/proto/arrow_pb2.py
  google/cloud/bigquery_storage_v1beta1/proto/arrow_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta1/proto/avro_pb2.py
  google/cloud/bigquery_storage_v1beta1/proto/avro_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta1/proto/read_options_pb2.py
  google/cloud/bigquery_storage_v1beta1/proto/read_options_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta1/proto/storage_pb2.py
  google/cloud/bigquery_storage_v1beta1/proto/storage_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta1/proto/table_reference_pb2.py
  google/cloud/bigquery_storage_v1beta1/proto/table_reference_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta2/gapic/big_query_read_client.py
  google/cloud/bigquery_storage_v1beta2/gapic/big_query_read_client_config.py
  google/cloud/bigquery_storage_v1beta2/gapic/transports/big_query_read_grpc_transport.py
  google/cloud/bigquery_storage_v1beta2/proto/arrow_pb2.py
  google/cloud/bigquery_storage_v1beta2/proto/arrow_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta2/proto/avro_pb2.py
  google/cloud/bigquery_storage_v1beta2/proto/avro_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta2/proto/storage_pb2.py
  google/cloud/bigquery_storage_v1beta2/proto/storage_pb2_grpc.py
  google/cloud/bigquery_storage_v1beta2/proto/stream_pb2.py
  google/cloud/bigquery_storage_v1beta2/proto/stream_pb2_grpc.py
  noxfile.py
  scripts/decrypt-secrets.sh
  synth.metadata
  tests/unit/gapic/v1beta1/test_big_query_storage_client_v1beta1.py
Labels: api: bigquerystorage, cla: yes, type: process

#56 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#55 chore: release 1.1.0
  CHANGELOG.md
  setup.py
Labels: api: bigquerystorage, autorelease: pending, cla: yes

#59 build: fix release build
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/trampoline.sh
  setup.py
Labels: cla: yes

#64 chore: Release v2.0.0
  CHANGELOG.md
  UPGRADING.md
  docs/bigquery_storage_v1/library.rst
  docs/bigquery_storage_v1/services.rst
  docs/bigquery_storage_v1/types.rst
  docs/index.rst
  google/cloud/bigquery/storage_v1/__init__.py
  google/cloud/bigquery_storage/__init__.py
  google/cloud/bigquery_storage/py.typed
  google/cloud/bigquery_storage_v1/client.py
  google/cloud/bigquery_storage_v1/gapic_types.py
  google/cloud/bigquery_storage_v1/py.typed
  google/cloud/bigquery_storage_v1/reader.py
  google/cloud/bigquery_storage_v1/services/__init__.py
  google/cloud/bigquery_storage_v1/services/big_query_read/__init__.py
  google/cloud/bigquery_storage_v1/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/__init__.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/base.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc_asyncio.py
  google/cloud/bigquery_storage_v1/types/__init__.py
  google/cloud/bigquery_storage_v1/types/arrow.py
  google/cloud/bigquery_storage_v1/types/avro.py
  google/cloud/bigquery_storage_v1/types/storage.py
  google/cloud/bigquery_storage_v1/types/stream.py
  noxfile.py
  samples/quickstart/quickstart.py
  samples/quickstart/quickstart_test.py
  samples/to_dataframe/main_test.py
  scripts/fixup_bigquery_storage_v1_keywords.py
  setup.py
  synth.metadata
  synth.py
  tests/system/v1/conftest.py
  tests/system/v1/test_reader_dataframe_v1.py
  tests/system/v1/test_reader_v1.py
  tests/unit/gapic/bigquery_storage_v1/__init__.py
  tests/unit/gapic/bigquery_storage_v1/test_big_query_read.py
  tests/unit/test_client_v1.py
  tests/unit/test_reader_v1.py
Labels: api: bigquerystorage, autorelease: pending, cla: yes
