Repository googleapis/python-bigquery-storage, pull requests merged in 2021-04, with the labels that each got.

#173 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#172 feat: updates for v1beta2 storage API - Updated comments on BatchCommitWriteStreams - Added new support Bigquery types BIGNUMERIC and INTERVAL to TableSchema - Added read rows schema in ReadRowsResponse - Misc comment updates
  google/cloud/bigquery_storage_v1beta2/proto/arrow.proto
  google/cloud/bigquery_storage_v1beta2/proto/avro.proto
  google/cloud/bigquery_storage_v1beta2/proto/protobuf.proto
  google/cloud/bigquery_storage_v1beta2/proto/storage.proto
  google/cloud/bigquery_storage_v1beta2/proto/stream.proto
  google/cloud/bigquery_storage_v1beta2/proto/table.proto
  google/cloud/bigquery_storage_v1beta2/types/protobuf.py
  google/cloud/bigquery_storage_v1beta2/types/storage.py
  google/cloud/bigquery_storage_v1beta2/types/stream.py
  google/cloud/bigquery_storage_v1beta2/types/table.py
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#176 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  samples/quickstart/noxfile.py
  samples/to_dataframe/noxfile.py
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full, samples

#178 feat: new JSON type through BigQuery Write
  google/cloud/bigquery_storage_v1beta2/proto/table.proto
  google/cloud/bigquery_storage_v1beta2/types/table.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#182 chore: prevent normalization of semver versioning
  setup.py
Labels: api: bigquerystorage, cla: yes

#183 chore(revert): revert preventing normalization
  setup.py
Labels: api: bigquerystorage, automerge, cla: yes

#180 build: use PyPI API token in secret manager
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#188 chore: add yoshi to CODEOWNERS
  .github/CODEOWNERS
Labels: api: bigquerystorage, cla: yes
