Repository googleapis/python-bigquery-storage, pull requests merged in 2021-05, with the labels that each got.

#193 chore: add library type to .repo-metadata.json
  .repo-metadata.json
Labels: api: bigquerystorage, cla: yes

#197 feat: Add ZSTD compression as an option for Arrow
  google/cloud/bigquery_storage_v1/proto/arrow.proto
  google/cloud/bigquery_storage_v1/proto/storage.proto
  google/cloud/bigquery_storage_v1/proto/stream.proto
  google/cloud/bigquery_storage_v1/types/arrow.py
  google/cloud/bigquery_storage_v1/types/stream.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#194 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: api: bigquerystorage, cla: yes

#200 fix(deps): add packaging requirement
  setup.py
  testing/constraints-3.6.txt
Labels: api: bigquerystorage, automerge, cla: yes
