Repository googleapis/python-bigquery-storage, pull requests merged in 2021-03, with the labels that each got.

#148 test: install pyopenssl for mtls testing
  noxfile.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#147 chore: update gapic-generator-python to 0.40.11
  google/cloud/bigquery_storage_v1/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/async_client.py
  synth.metadata
  tests/unit/gapic/bigquery_storage_v1/__init__.py
  tests/unit/gapic/bigquery_storage_v1/test_big_query_read.py
  tests/unit/gapic/bigquery_storage_v1beta2/__init__.py
  tests/unit/gapic/bigquery_storage_v1beta2/test_big_query_read.py
  tests/unit/gapic/bigquery_storage_v1beta2/test_big_query_write.py
Labels: api: bigquerystorage, cla: yes, context: full

#153 chore: updates to gapic generator
  google/cloud/bigquery_storage_v1/types/__init__.py
  google/cloud/bigquery_storage_v1beta2/types/__init__.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#149 chore: exclude tarball from code generation
  synth.py
Labels: api: bigquerystorage, automerge, cla: yes, context: none

#156 chore: add pre-commit-config to renovate ignore paths
  renovate.json
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#155 test: use job metadata to avoid test flakes
  tests/system/conftest.py
  tests/system/reader/test_reader.py
Labels: api: bigquerystorage, cla: yes

#160 test: add retry for rate limiting of load jobs
  tests/system/__init__.py
  tests/system/conftest.py
  tests/system/helpers.py
  tests/system/reader/__init__.py
  tests/system/reader/test_reader.py
Labels: api: bigquerystorage, automerge, cla: yes

#159 build(python): fail nox sessions if a python version is missing
  noxfile.py
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#164 fix: use correct retry deadline
  google/cloud/bigquery_storage_v1/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/base.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc_asyncio.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/base.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/grpc_asyncio.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/async_client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/base.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/grpc.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/grpc_asyncio.py
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#165 deps: update minimum pandas to 0.21.1
  .pre-commit-config.yaml
  noxfile.py
  setup.py
  synth.metadata
  testing/constraints-3.6.txt
  tests/unit/test_reader_v1.py
  tests/unit/test_reader_v1_arrow.py
Labels: api: bigquerystorage, cla: yes, context: full

#166 feat: add a Arrow compression options (Only LZ4 for now)
  google/cloud/bigquery_storage/__init__.py
  google/cloud/bigquery_storage_v1/proto/arrow.proto
  google/cloud/bigquery_storage_v1/proto/avro.proto
  google/cloud/bigquery_storage_v1/proto/storage.proto
  google/cloud/bigquery_storage_v1/proto/stream.proto
  google/cloud/bigquery_storage_v1/types/__init__.py
  google/cloud/bigquery_storage_v1/types/arrow.py
  google/cloud/bigquery_storage_v1/types/storage.py
  google/cloud/bigquery_storage_v1/types/stream.py
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full
