Repository googleapis/python-bigquery-storage, pull requests merged in 2021-01, with the labels that each got.

#106 fix: skip some system tests for mtls testing
  tests/system/v1/conftest.py
Labels: api: bigquerystorage, cla: yes

#107 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: api: bigquerystorage, cla: yes

#99 test: test on Python 3.9
  docs/conf.py
  noxfile.py
  synth.metadata
  tests/unit/__init__.py
  tests/unit/helpers.py
  tests/unit/test_reader_v1.py
  tests/unit/test_reader_v1_arrow.py
Labels: api: bigquerystorage, cla: yes, context: partial

#112 chore: remove manual workaround for response size validation
  .coveragerc
  .flake8
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .pre-commit-config.yaml
  .trampolinerc
  CONTRIBUTING.rst
  LICENSE
  docs/_static/custom.css
  docs/bigquery_storage_v1/big_query_read.rst
  docs/bigquery_storage_v1/services.rst
  docs/bigquery_storage_v1/types.rst
  google/cloud/bigquery_storage_v1/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/client.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/__init__.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1/services/big_query_read/transports/grpc_asyncio.py
  google/cloud/bigquery_storage_v1/types/__init__.py
  google/cloud/bigquery_storage_v1/types/storage.py
  google/cloud/bigquery_storage_v1/types/stream.py
  noxfile.py
  samples/quickstart/noxfile.py
  samples/to_dataframe/noxfile.py
  synth.metadata
  synth.py
  tests/unit/gapic/bigquery_storage_v1/test_big_query_read.py
Labels: api: bigquerystorage, cla: yes

#113 feat: add clients for v1beta2 endpoint
  docs/bigquery_storage_v1beta2/big_query_read.rst
  docs/bigquery_storage_v1beta2/big_query_write.rst
  docs/bigquery_storage_v1beta2/services.rst
  docs/bigquery_storage_v1beta2/types.rst
  docs/index.rst
  google/cloud/bigquery_storage_v1beta2/proto/arrow.proto
  google/cloud/bigquery_storage_v1beta2/proto/avro.proto
  google/cloud/bigquery_storage_v1beta2/proto/protobuf.proto
  google/cloud/bigquery_storage_v1beta2/proto/storage.proto
  google/cloud/bigquery_storage_v1beta2/proto/stream.proto
  google/cloud/bigquery_storage_v1beta2/proto/table.proto
  google/cloud/bigquery_storage_v1beta2/py.typed
  google/cloud/bigquery_storage_v1beta2/services/__init__.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/__init__.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/async_client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/__init__.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/base.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/grpc.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_read/transports/grpc_asyncio.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/__init__.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/async_client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/client.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/__init__.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/base.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/grpc.py
  google/cloud/bigquery_storage_v1beta2/services/big_query_write/transports/grpc_asyncio.py
  google/cloud/bigquery_storage_v1beta2/types/__init__.py
  google/cloud/bigquery_storage_v1beta2/types/arrow.py
  google/cloud/bigquery_storage_v1beta2/types/avro.py
  google/cloud/bigquery_storage_v1beta2/types/protobuf.py
  google/cloud/bigquery_storage_v1beta2/types/storage.py
  google/cloud/bigquery_storage_v1beta2/types/stream.py
  google/cloud/bigquery_storage_v1beta2/types/table.py
  synth.py
  tests/unit/gapic/bigquery_storage_v1beta2/__init__.py
  tests/unit/gapic/bigquery_storage_v1beta2/test_big_query_read.py
  tests/unit/gapic/bigquery_storage_v1beta2/test_big_query_write.py
Labels: api: bigquerystorage, automerge, cla: yes

#114 docs: request only a single stream in dataframe example
  samples/to_dataframe/main_test.py
Labels: api: bigquerystorage, cla: yes

#73 docs: add note about Arrow blocks to README
  README.rst
Labels: api: bigquerystorage, automerge, cla: yes

#117 feat: add manual wrapper for v1beta2 read client
  docs/bigquery_storage_v1beta2/library.rst
  docs/index.rst
  google/cloud/bigquery_storage_v1beta2/__init__.py
  google/cloud/bigquery_storage_v1beta2/client.py
  synth.py
  tests/system/conftest.py
  tests/system/reader/conftest.py
  tests/system/reader/test_reader.py
  tests/system/reader/test_reader_dataframe.py
Labels: api: bigquerystorage, cla: yes

#124 docs: remove required session variable to fix publish
  .trampolinerc
Labels: api: bigquerystorage, automerge, cla: yes

#129 chore: refresh synth.metadata
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: partial

#133 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: bigquerystorage, cla: yes
