Repository googleapis/python-bigquery-storage, pull requests merged in 2022-06, with the labels that each got.

#456 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: bigquerystorage, size: xs

#457 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: bigquerystorage, size: s

#459 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: bigquerystorage, size: s

#460 fix(deps): require protobuf<4.0.0 on v1 branch
  setup.py
Labels: api: bigquerystorage, size: xs

#414 fix: handle AttributeError in bigquery_storage writer
  google/cloud/bigquery_storage_v1/writer.py
  google/cloud/bigquery_storage_v1beta2/writer.py
Labels: api: bigquerystorage, size: m
