Repository googleapis/python-bigquery-storage, pull requests merged in 2022-08, with the labels that each got.

#481 fix(deps): drop freezegun dependency in extras
  setup.py
  tests/unit/test_writer_v1.py
  tests/unit/test_writer_v1beta2.py
Labels: api: bigquerystorage, size: s

#486 fix(deps): allow protobuf < 5.0.0
  setup.py
  testing/constraints-3.7.txt
Labels: api: bigquerystorage, automerge, size: xs

#485 test: Remove Use Of check_datetimelike_compat Flag
  tests/unit/test_reader_v1.py
Labels: api: bigquerystorage, size: xs
