Repository googleapis/python-bigquery-storage, pull requests merged in 2024-04, with the labels that each got.

#769 testing: use arbitrary equality for pinned requirement versions
  samples/quickstart/requirements-test.txt
  samples/snippets/requirements-test.txt
  samples/to_dataframe/requirements-test.txt
  samples/to_dataframe/requirements.txt
Labels: api: bigquerystorage, size: s

#765 fix: make read_session no longer DEPRECATED
  google/cloud/bigquery_storage_v1/reader.py
Labels: api: bigquerystorage, size: s

#740 fix: add google-auth as a direct dependency
  setup.py
  testing/constraints-3.7.txt
Labels: api: bigquerystorage, size: xs

#780 feat: add stream write samples for range
  samples/snippets/append_rows_proto2.py
  samples/snippets/sample_data.proto
  samples/snippets/sample_data_pb2.py
  samples/snippets/sample_data_schema.json
Labels: api: bigquerystorage, samples, size: m
