Repository googleapis/python-bigquery-storage, pull requests merged in 2025-08, with the labels that each got.

#965 test: exclude lint.yml and docs.yml from renovate bot
  renovate.json
Labels: api: bigquerystorage, size: xs

#964 feat: add support for Python 3.13
  .github/sync-repo-settings.yaml
  owlbot.py
  setup.py
Labels: api: bigquerystorage, automerge, size: xs

#970 chore: test that ServiceUnavailable is retried
  tests/unit/test_read_client_v1.py
Labels: api: bigquerystorage, size: m
