Repository googleapis/python-bigquery-storage, pull requests merged in 2025-03, with the labels that each got.

#904 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: bigquerystorage, size: xl

#905 fix: Allow protobuf 6.x
  setup.py
Labels: api: bigquerystorage, size: s

#909 fix: correct user agent header to track calls as veneer instead of gapic
  google/cloud/bigquery_storage_v1/client.py
  google/cloud/bigquery_storage_v1beta2/client.py
  tests/unit/test_client_v1.py
Labels: api: bigquerystorage, size: m

#913 fix: remove setup.cfg configuration for creating universal wheels
  setup.cfg
Labels: api: bigquerystorage, automerge, size: s

#901 feat: link stream to use _Connection
  google/cloud/bigquery_storage_v1/writer.py
  tests/system/conftest.py
  tests/system/test_writer.py
  tests/unit/test_writer_v1.py
Labels: api: bigquerystorage, size: l

#915 feat: sample for AppendRowsStream with Arrow
  google/cloud/bigquery_storage_v1/writer.py
  samples/conftest.py
  samples/pyarrow/__init__.py
  samples/pyarrow/append_rows_with_arrow.py
  samples/pyarrow/append_rows_with_arrow_test.py
  samples/pyarrow/noxfile.py
  samples/pyarrow/requirements-test.txt
  samples/pyarrow/requirements.txt
  tests/unit/test_writer_v1.py
Labels: api: bigquerystorage, samples, size: l

#919 test: make pyarrow sample less flaky
  samples/conftest.py
Labels: api: bigquerystorage, samples, size: xs
